import os

def generate_lambda_signature_parsers():
    """
    为 lambda_signature_parser 生成 C++ 模板特化，
    以覆盖其 operator() 的所有可能的限定符组合。
    """
    # 定义所有可能的限定符
    cv_qualifiers = [
        ("", {"const": False, "volatile": False}),
        (" const", {"const": True, "volatile": False}),
        (" volatile", {"const": False, "volatile": True}),
        (" const volatile", {"const": True, "volatile": True}),
    ]

    ref_qualifiers = [
        ("", {"lvalue": False, "rvalue": False}),
        (" &", {"lvalue": True, "rvalue": False}),
        (" &&", {"lvalue": False, "rvalue": True}),
    ]

    noexcept_qualifiers = [
        ("", {"noexcept": False}),
        (" noexcept", {"noexcept": True}),
    ]

    # C++ 模板字符串
    template = """template <typename R, typename C, typename... Args>
struct lambda_signature_parser<R (C::*)(Args...){qualifiers}>
{{
    using return_type = R;
    using args_tuple = std::tuple<Args...>;
    static constexpr bool is_const = {is_const};
    static constexpr bool is_volatile = {is_volatile};
    static constexpr bool is_lvalue_ref = {is_lvalue};
    static constexpr bool is_rvalue_ref = {is_rvalue};
    static constexpr bool is_noexcept = {is_noexcept};
}};"""

    output = []
    output.append("// This file is generated by generate_lambda_parsers.py. DO NOT EDIT MANUALLY.\n")

    for cv_text, cv_flags in cv_qualifiers:
        for ref_text, ref_flags in ref_qualifiers:
            for noexcept_text, noexcept_flags in noexcept_qualifiers:
                
                # 基础的无限定符版本已经在 parser.hpp 中定义，跳过以避免重定义
                if not cv_text and not ref_text and not noexcept_text:
                    continue

                qualifiers_str = f"{cv_text}{ref_text}{noexcept_text}"
                
                # 组合所有布尔标志
                all_flags = {**cv_flags, **ref_flags, **noexcept_flags}

                # 格式化模板
                specialization = template.format(
                    qualifiers=qualifiers_str,
                    is_const=str(all_flags["const"]).lower(),
                    is_volatile=str(all_flags["volatile"]).lower(),
                    is_lvalue=str(all_flags["lvalue"]).lower(),
                    is_rvalue=str(all_flags["rvalue"]).lower(),
                    is_noexcept=str(all_flags["noexcept"]).lower(),
                )
                output.append(specialization)

    return "\n".join(output)

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "lambda_signature_parser.inc")
    
    print(f"Generating lambda signature parsers to {output_path}...")
    generated_code = generate_lambda_signature_parsers()
    with open(output_path, "w") as f:
        f.write(generated_code)
    print("Generation complete.")
